name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Instal pnpm
        uses: pnpm/action-setup@v6
      - name: Use Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24.18.0
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm lint

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Instal pnpm
        uses: pnpm/action-setup@v6
      - name: Use Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24.18.0
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Format
        run: pnpm format

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Instal pnpm
        uses: pnpm/action-setup@v6
      - name: Use Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24.18.0
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Check
        run: pnpm check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Instal pnpm
        uses: pnpm/action-setup@v6
      - name: Use Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24.18.0
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Test
        run: ${{ (github.ref == 'refs/heads/main' && github.event_name == 'push') && 'pnpm test:coverage' || 'pnpm test' }}
      - name: Upload results to Codecov
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
